### ISSUE TITLE
古橋に編集権限を与える

### ISSUE THREAD

**Issue by mapconcierge** [AyameO/TeachOSM4KYOTO#2]
＞  @AyameO 
このレポジトリに @mapconcierge アカウントを  collaborator として登録お願いします。

**Comment by mapconcierge** [comment]
https://github.com/AyameO/TeachOSM4KYOTO の右上にある Setting のところから。

**Comment by AyameO** [comment]
かしこまりました。
招待いたしました。
![default](https://user-images.githubusercontent.com/13360878/35205515-07bace12-ff79-11e7-8fe3-2cd7be4b7b4d.png)

**Comment by mapconcierge** [comment]
ありがとう！
この Issueは閉じます。
